# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09f63ded24552d03bec07b05a61fad170851316b9a5a8d224c1306a04c772ebc7625a32e55b2a967f609af7206c797c0ec5bb7462a1ba838630b21a745fb1420

test:
  secret_key_base: 93a84b667bce9905485aca28aff79505581fb552c7a8c0ccd2eafb18d2d667a9eb404672ae0dea303ca188e12461394b6f454a9445651d558928e1598e2cd086

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
